name = "Arris"
description = "A blog theme inspired by Arc'Teryx Veilance Arris Jacket, for Zola"
license = "MIT"
homepage = "https://github.com/dantewang/zola-theme-arris"
min_version = "0.15.3"
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Dante Wang"
homepage = "https://dante.io"

[original]
author =  "Dante Wang"
homepage = "https://dante.io/"
repo = "https://github.com/dantewang/hugo-theme-arris"